services:
  - type: web
    name: scrs-federasi-kewangan
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.13.0"
